# Generated by Django 3.2.6 on 2021-08-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=30)),
                ('college_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('mob_num', models.CharField(max_length=10, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('hometown', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('test_date', models.DateField()),
            ],
        ),
    ]
