# Generated by Django 3.2.6 on 2021-08-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='test_date',
        ),
    ]
