# Generated by Django 3.2.6 on 2021-09-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotional_intelligence',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='test_date',
        ),
        migrations.AddField(
            model_name='emotional_intelligence',
            name='eitest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intellectual_capacity',
            name='ictest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meta_cognitive_test',
            name='mcttest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personal_test',
            name='pttest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='middle_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
