# Generated by Django 3.2.6 on 2021-09-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='middle_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
