# Generated by Django 3.2.6 on 2021-08-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='branch',
            new_name='branch_name',
        ),
        migrations.RenameField(
            model_name='student_details',
            old_name='l_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student_details',
            old_name='mob_num',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='student_details',
            old_name='f_name',
            new_name='student_year',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='year',
        ),
        migrations.AddField(
            model_name='student_details',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student_details',
            name='middle_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
