# Generated by Django 3.2.6 on 2021-08-19 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210819_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='f_name',
            new_name='name',
        ),
    ]
