# Generated by Django 3.2.6 on 2021-08-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_f_name_student_details_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student_details',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='student_details',
            old_name='mob_num',
            new_name='mobile_num',
        ),
    ]
